services:
  - type: web
    name: gv-legacy-combined
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /database/*
        destination: /database/database/index.html
      - type: rewrite
        source: /map/*
        destination: /map/index.html
      - type: rewrite
        source: /*
        destination: /index.html
